const DEMO=`<hill version="DSJ4-1.10.0">
<inrun><profile e="91.5" es="15" t="6.43" gamma="33.5" alpha="10.5" r1="105" s="2.5" b1="2.0" z0="0" l="6.5" f="3.0"/></inrun>
<dhill><profile alpha="6.28" h="62.93" n="107.41" l1="16.04" l2="13.38" a="87.5" beta-p="37.7" beta="34.7" beta-l="32.2" rl="306.15" r2="73.22" b0="9.5" bk="23.37" ba="25" hr="10" nr="60" ar="10" k="120" hs="134"/></dhill>
</hill>`;
const $=id=>document.getElementById(id);
const canvas=$('plot'),ctx=canvas.getContext('2d'),tip=$('tooltip');
let hills={A:null,B:null};
let view={cx:50,cy:-20,scale:4};
let dragging=false,last={x:0,y:0};
function deg(v){return Number(v)*Math.PI/180}
function hasNum(o,k){return !!o && o[k]!==undefined && o[k]!==null && o[k]!=='' && Number.isFinite(Number(o[k]))}
function num(o,k,d=0){return hasNum(o,k)?Number(o[k]):d}
function firstNum(o,keys,d=0){for(const k of keys)if(hasNum(o,k))return Number(o[k]);return d}
function attrs(el){const o={};if(!el)return o;for(const a of el.attributes)o[a.name]=Number.isFinite(Number(a.value))&&a.value.trim()!==''?Number(a.value):a.value;return o}
function parseHill(xml,name='DSJ4 hill'){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('Nieprawidłowy XML');const ir=attrs(doc.querySelector('inrun > profile'));const dh=attrs(doc.querySelector('dhill > profile'));if(!Object.keys(ir).length||!Object.keys(dh).length)throw new Error('Brak inrun/profile albo dhill/profile');const geometry=buildGeometry(ir,dh);return {name,ir,dh,geometry,rawXml:xml};}
function linePoints(a,b,N=30){const out=[];for(let i=0;i<=N;i++){const t=i/N;out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t})}return out;}
function hermiteX(x0,y0,m0,x1,y1,m1,N=100){if(Math.abs(x1-x0)<1e-9)return linePoints({x:x0,y:y0},{x:x1,y:y1},N);const dx=x1-x0,out=[];for(let i=0;i<=N;i++){const t=i/N,h00=2*t*t*t-3*t*t+1,h10=t*t*t-2*t*t+t,h01=-2*t*t*t+3*t*t,h11=t*t*t-t*t;out.push({x:x0+t*dx,y:h00*y0+h10*dx*m0+h01*y1+h11*dx*m1});}return out;}
function arcFromTangent(p0,length,a0,a1,N=70){if(length<=0)return [{x:p0.x,y:p0.y}];if(Math.abs(a0-a1)<1e-10)return linePoints(p0,{x:p0.x+length*Math.cos(a0),y:p0.y-length*Math.sin(a0)},N);const out=[{x:p0.x,y:p0.y}],ds=length/N;let x=p0.x,y=p0.y;for(let i=1;i<=N;i++){const q=(i-.5)/N,a=a0+(a1-a0)*q;x+=Math.cos(a)*ds;y-=Math.sin(a)*ds;out.push({x,y});}return out;}
function deriveP(K,l1,bp,bk){if(l1<=0)return {...K};const d=bp-bk;if(Math.abs(d)<1e-10)return {x:K.x-l1*Math.cos(bk),y:K.y+l1*Math.sin(bk)};const R=l1/d;const dx=R*(Math.sin(bp)-Math.sin(bk));const dy=R*(Math.cos(bp)-Math.cos(bk));return {x:K.x-dx,y:K.y-dy};}
function deriveL(K,l2,bk,bl){if(l2<=0)return {...K};const d=bk-bl;if(Math.abs(d)<1e-10)return {x:K.x+l2*Math.cos(bk),y:K.y-l2*Math.sin(bk)};const R=l2/d;const dx=R*(Math.sin(bk)-Math.sin(bl));const dy=R*(Math.cos(bk)-Math.cos(bl));return {x:K.x+dx,y:K.y+dy};}
function solve3(A,b){const M=A.map((r,i)=>[...r,b[i]]);for(let c=0;c<3;c++){let p=c;for(let r=c+1;r<3;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-12)return null;[M[c],M[p]]=[M[p],M[c]];const q=M[c][c];for(let j=c;j<4;j++)M[c][j]/=q;for(let r=0;r<3;r++)if(r!==c){const f=M[r][c];for(let j=c;j<4;j++)M[r][j]-=f*M[c][j]}}return [M[0][3],M[1][3],M[2][3]];}
function lowerTransitionDefault(L,betaL,r2,N=100){if(!(r2>0)||!(betaL>0)){const U={x:L.x+Math.max(20,r2||20),y:L.y};return {points:linePoints(L,U,N),U,mode:'fallback'};}const C={x:L.x+r2*Math.sin(betaL),y:L.y+r2*Math.cos(betaL)};const U={x:C.x,y:C.y-r2};const a0=Math.atan2(L.y-C.y,L.x-C.x);const a1=-Math.PI/2;let da=a1-a0;while(da<=0)da+=Math.PI*2;if(da>Math.PI)da-=Math.PI*2;const out=[];for(let i=0;i<=N;i++){const a=a0+da*i/N;out.push({x:C.x+r2*Math.cos(a),y:C.y+r2*Math.sin(a)});}return {points:out,U,mode:'r2 → łuk kołowy'};}
function lowerTransitionToExactU(L,U,betaL,r2,N=110){const dx=U.x-L.x;if(!(dx>0))return {points:linePoints(L,U,N),mode:'bad-endpoint'};const points=hermiteX(L.x,L.y,-Math.tan(betaL),U.x,U.y,0,N);return {points,mode:'r2x/r2y → U exact; gładka styczna L→U'};}
function buildInrun(ir){const alpha=deg(num(ir,'alpha',10)),gamma=deg(num(ir,'gamma',32));const t=num(ir,'t',5),r1=num(ir,'r1',80),e=num(ir,'e',80);const E2={x:-t*Math.cos(alpha),y:t*Math.sin(alpha)};const delta=Math.max(0,gamma-alpha);let transition=[],E1=E2,transitionLen=0;if(r1>0&&delta>1e-8){const d=2*r1*Math.sin(delta)*Math.cos(delta)**2;const C=Math.tan(delta)/(3*d*d);const f=Math.tan(delta)*d/3;transitionLen=d*(1+0.1*Math.tan(delta)**2);E1={x:-(t*Math.cos(alpha)+f*Math.sin(gamma)+d*Math.cos(gamma)),y:t*Math.sin(alpha)-f*Math.cos(gamma)+d*Math.sin(gamma)};for(let i=0;i<=100;i++){const xi=d*i/100,eta=C*xi**3;transition.push({x:E1.x+xi*Math.cos(gamma)+eta*Math.sin(gamma),y:E1.y-xi*Math.sin(gamma)+eta*Math.cos(gamma)});}}else transition=[E2];const straightLen=Math.max(0,e-t-transitionLen);const S={x:E1.x-straightLen*Math.cos(gamma),y:E1.y+straightLen*Math.sin(gamma)};const straight=linePoints(S,E1,40);const table=linePoints(E2,{x:0,y:0},25);return {points:[...straight,...transition.slice(1),...table.slice(1)],marks:{S,E1,E2,T:{x:0,y:0}},transitionLen};}
