function prettyXml(xml){xml=String(xml??'').replace(/\r\n/g,'\n').trim();if(!xml)return '';const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('XML zawiera błąd składni');const raw=new XMLSerializer().serializeToString(doc);const tokens=raw.replace(/>\s*</g,'><').replace(/(>)(<)(\/*)/g,'$1\n$2$3').split('\n').map(x=>x.trim()).filter(Boolean);let level=0,out=[];for(const token of tokens){const close=/^<\//.test(token);const open=/^<[^!?/][^>]*>$/.test(token)&&!/\/>$/.test(token)&&!/^<[^>]+>.*<\/[^>]+>$/.test(token);if(close)level=Math.max(0,level-1);out.push('  '.repeat(level)+token);if(open)level++;}return out.join('\n');}
function escHtml(x){return String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function highlightXml(xml){const escaped=escHtml(xml);return escaped.replace(/(&lt;!--[\s\S]*?--&gt;)|(&lt;\?[\s\S]*?\?&gt;)|(&lt;\/?)([A-Za-z_][\w:.-]*)([\s\S]*?)(&gt;)/g,(all,comment,decl,open,tag,inside,close)=>{if(comment)return `<span class="x-comment">${comment}</span>`;if(decl)return `<span class="x-decl">${decl}</span>`;let attrs=inside.replace(/(\s+)([A-Za-z_][\w:.-]*)(\s*=\s*)(&quot;[^&]*?&quot;|'[^']*?')/g,(m,sp,name,eq,val)=>{const vv=val.replace(/(&quot;|')(-?\d+(?:\.\d+)?)(\1)/g,(z,q,n)=>`${q}<span class="x-number">${n}</span>${q}`);return `${sp}<span class="x-attr">${name}</span><span class="x-punct">${eq}</span><span class="x-string">${vv}</span>`;});return `<span class="x-punct">${open}</span><span class="x-tag">${tag}</span>${attrs}<span class="x-punct">${close}</span>`;});}
function updateHighlight(){const ta=$('xmlText'),hi=$('xmlHighlight');if(!ta||!hi)return;hi.innerHTML=highlightXml(ta.value)+(ta.value.endsWith('\n')?' ':'');hi.scrollTop=ta.scrollTop;hi.scrollLeft=ta.scrollLeft;}
function updateLineNumbers(){const ta=$('xmlText'),ln=$('lineNums');if(!ta||!ln)return;const count=Math.max(1,(ta.value.match(/\n/g)||[]).length+1);ln.textContent=Array.from({length:count},(_,i)=>i+1).join('\n');ln.scrollTop=ta.scrollTop;updateHighlight();}
function setEditorXml(xml,format=true){let text=String(xml??'');if(format&&text.trim()){try{text=prettyXml(text)}catch(e){}}$('xmlText').value=text;updateLineNumbers();validateEditorXml(false);}
function copyHillToEditor(which){const h=hills[which];if(!h){alert(`Skocznia ${which} nie jest wczytana`);return}setEditorXml(h.rawXml||'',true);$('xmlStatus').textContent=`Wczytano ${which}: ${h.name}`;}
function formatEditorXml(){try{$('xmlText').value=prettyXml($('xmlText').value);updateLineNumbers();validateEditorXml(false)}catch(e){$('xmlStatus').className='xml-invalid';$('xmlStatus').textContent=e.message}}
function validateEditorXml(showAlert=false){const text=$('xmlText').value.trim(),st=$('xmlStatus');if(!text){st.className='small';st.textContent='Edytor pusty';return false}const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror')){st.className='xml-invalid';st.textContent='Błąd XML — sprawdź składnię';if(showAlert)alert(st.textContent);return false;}if(!doc.querySelector('inrun > profile')||!doc.querySelector('dhill > profile')){st.className='xml-invalid';st.textContent='XML poprawny, ale brak inrun/profile lub dhill/profile';if(showAlert)alert(st.textContent);return false;}st.className='xml-valid';st.textContent='XML poprawny';return true;}
function saveEditorXml(){if(!validateEditorXml(true))return;const text=$('xmlText').value;const blob=new Blob([text],{type:'application/xml;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dsj4_hill_edited.xml';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function bindEditor(){const ta=$('xmlText'),file=$('editorFile');ta.addEventListener('input',()=>{updateLineNumbers();validateEditorXml(false)});ta.addEventListener('scroll',()=>{$('lineNums').scrollTop=ta.scrollTop;$('xmlHighlight').scrollTop=ta.scrollTop;$('xmlHighlight').scrollLeft=ta.scrollLeft;});ta.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const a=ta.selectionStart,b=ta.selectionEnd;ta.value=ta.value.slice(0,a)+'  '+ta.value.slice(b);ta.selectionStart=ta.selectionEnd=a+2;updateLineNumbers();}});file.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;setEditorXml(await f.text(),true);$('xmlStatus').textContent=`Wczytano do edytora: ${f.name}`;file.value='';});}
function loadDemo(which){let x=DEMO;if(which==='B'){x=x.replace('h="62.93"','h="61.2"').replace('n="107.41"','n="108.2"').replace('beta="34.7"','beta="33.8"').replace('r2="73.22"','r2="82"').replace('hs="134"','hs="138"');}setHill(which,parseHill(x,which==='A'?'Demo K120 / HS134':'Demo wariant B'));}
function loadText(which){try{if(!validateEditorXml(true))return;const xml=$('xmlText').value;setHill(which,parseHill(xml,`Edytowany XML ${which}`));}catch(e){alert(e.message)}}
function bindFile(id,which){$(id).addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const text=await f.text();setHill(which,parseHill(text,f.name));if(!$('xmlText').value.trim())setEditorXml(text,true);}catch(err){alert(err.message)}});}
bindFile('fileA','A');bindFile('fileB','B');['showA','showB','showConstruction'].forEach(id=>$(id).addEventListener('change',draw));
