function allVisiblePoints(){const out=[];for(const w of ['A','B']){if(!hills[w]||!$('show'+w).checked)continue;out.push(...hills[w].geometry.inrun,...hills[w].geometry.landing);}return out;}
function bounds(){const pp=allVisiblePoints();if(!pp.length)return {minx:-100,maxx:220,miny:-100,maxy:100};return {minx:Math.min(...pp.map(p=>p.x)),maxx:Math.max(...pp.map(p=>p.x)),miny:Math.min(...pp.map(p=>p.y)),maxy:Math.max(...pp.map(p=>p.y))};}
function resize(){const r=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
addEventListener('resize',resize);
function resetView(){const b=bounds(),r=canvas.getBoundingClientRect(),pad=50;const sx=(r.width-2*pad)/(b.maxx-b.minx||1),sy=(r.height-2*pad)/(b.maxy-b.miny||1);view.scale=Math.max(.35,Math.min(sx,sy));view.cx=(b.minx+b.maxx)/2;view.cy=(b.miny+b.maxy)/2;draw();}
function worldToScreen(p){const r=canvas.getBoundingClientRect();return {x:r.width/2+(p.x-view.cx)*view.scale,y:r.height/2-(p.y-view.cy)*view.scale};}
function screenToWorld(x,y){const r=canvas.getBoundingClientRect();return {x:view.cx+(x-r.width/2)/view.scale,y:view.cy-(y-r.height/2)/view.scale};}
function niceStep(target){const pow=Math.pow(10,Math.floor(Math.log10(Math.max(target,.0001)))),n=target/pow;return (n<2?1:n<5?2:5)*pow;}
function drawGrid(){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#0d1425';ctx.fillRect(0,0,r.width,r.height);const step=niceStep(80/view.scale),w0=screenToWorld(0,r.height),w1=screenToWorld(r.width,0);ctx.strokeStyle='#263451';ctx.lineWidth=1;ctx.font='11px system-ui';ctx.fillStyle='#8290aa';for(let x=Math.floor(w0.x/step)*step;x<=w1.x;x+=step){const sp=worldToScreen({x,y:0});ctx.beginPath();ctx.moveTo(sp.x,0);ctx.lineTo(sp.x,r.height);ctx.stroke();ctx.fillText(`${Math.round(x*10)/10} m`,sp.x+4,r.height-8);}for(let y=Math.floor(w0.y/step)*step;y<=w1.y;y+=step){const sp=worldToScreen({x:0,y});ctx.beginPath();ctx.moveTo(0,sp.y);ctx.lineTo(r.width,sp.y);ctx.stroke();ctx.fillText(`${Math.round(y*10)/10} m`,5,sp.y-4);}const o=worldToScreen({x:0,y:0});ctx.strokeStyle='#60708e';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(o.x,0);ctx.lineTo(o.x,r.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,o.y);ctx.lineTo(r.width,o.y);ctx.stroke();}
function drawPath(points,color,width=2.4){if(!points?.length)return;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>{const s=worldToScreen(p);i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y)});ctx.stroke();}
function drawMarker(p,label,color,filled=false){if(!p)return;const s=worldToScreen(p);ctx.save();ctx.strokeStyle=color;ctx.fillStyle=filled?color:'#0d1425';ctx.lineWidth=filled?1.1:2;ctx.beginPath();ctx.arc(s.x,s.y,filled?5:4.7,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.font=(filled?'bold ':'')+'11px system-ui';ctx.fillText(label,s.x+7,s.y-7);ctx.restore();}
function pointAtLandingDistance(h,distance){if(!h||!Number.isFinite(distance)||distance<0)return null;const pts=h.geometry.landing;let acc=0;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],seg=Math.hypot(b.x-a.x,b.y-a.y);if(acc+seg>=distance){const t=seg?Math.max(0,Math.min(1,(distance-acc)/seg)):0;return {x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,distance};}acc+=seg;}return null;}
function landingAtX(h,x){if(!h)return null;const pts=h.geometry.landing;let acc=0;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],seg=Math.hypot(b.x-a.x,b.y-a.y);const lo=Math.min(a.x,b.x),hi=Math.max(a.x,b.x);if(x>=lo-1e-9&&x<=hi+1e-9&&Math.abs(b.x-a.x)>1e-9){const t=(x-a.x)/(b.x-a.x);if(t>=-1e-6&&t<=1+1e-6){const tc=Math.max(0,Math.min(1,t));return {x,y:a.y+tc*(b.y-a.y),distance:acc+tc*seg};}}acc+=seg;}return null;}
function drawHill(h,color){if(!h)return;drawPath(h.geometry.inrun,color,2.35);drawPath(h.geometry.landing,color,2.35);const m=h.geometry.marks;if(m.T&&m.sillFoot&&num(h.ir,'s',0)>0){const a=worldToScreen(m.T),b=worldToScreen(m.sillFoot);ctx.save();ctx.strokeStyle=color;ctx.globalAlpha=.55;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore();}drawMarker(m.T,'T',color,false);if($('showConstruction').checked){drawMarker(m.P,'P geom','#41d6ff',false);drawMarker(m.K,'K geom','#d98cff',false);drawMarker(m.L,'L','#79e37d',false);drawMarker(m.U,'U','#ffd76a',false);}if(hasNum(h.dh,'p')){const p=pointAtLandingDistance(h,num(h.dh,'p'));if(p)drawMarker(p,'P'+h.dh.p,'#ff4d5a',true);}if(hasNum(h.dh,'k')){const p=pointAtLandingDistance(h,num(h.dh,'k'));if(p)drawMarker(p,'K'+h.dh.k,'#ff4d5a',true);}if(hasNum(h.dh,'hs')&&(!hasNum(h.dh,'k')||num(h.dh,'hs')!==num(h.dh,'k'))){const p=pointAtLandingDistance(h,num(h.dh,'hs'));if(p)drawMarker(p,'HS'+h.dh.hs,'#ff4d5a',true);}if(num(h.ir,'s',0)>0){const mid={x:0,y:-num(h.ir,'s')/2},sp=worldToScreen(mid);ctx.save();ctx.fillStyle=color;ctx.font='11px system-ui';ctx.fillText(`s=${num(h.ir,'s').toFixed(2)} m`,sp.x+7,sp.y);ctx.restore();}}
function draw(){drawGrid();if(hills.A&&$('showA').checked)drawHill(hills.A,'#62a8ff');if(hills.B&&$('showB').checked)drawHill(hills.B,'#ffb35c')}
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,w=screenToWorld(mx,my);const f=Math.exp(-e.deltaY*.001);view.scale=Math.max(.2,Math.min(35,view.scale*f));const w2=screenToWorld(mx,my);view.cx+=w.x-w2.x;view.cy+=w.y-w2.y;draw();},{passive:false});
canvas.addEventListener('mousedown',e=>{dragging=true;last={x:e.clientX,y:e.clientY}});addEventListener('mouseup',()=>dragging=false);addEventListener('mousemove',e=>{if(!dragging)return;view.cx-=(e.clientX-last.x)/view.scale;view.cy+=(e.clientY-last.y)/view.scale;last={x:e.clientX,y:e.clientY};draw();});
canvas.addEventListener('mousemove',e=>{if(dragging)return;const r=canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,w=screenToWorld(mx,my);const la=landingAtX(hills.A,w.x),lb=landingAtX(hills.B,w.x);let lines=[`x poziome: ${w.x.toFixed(2)} m`];if(la){lines.push(`A: y ${la.y.toFixed(2)} m`);lines.push(`A: po zeskoku ${la.distance.toFixed(2)} m`)}if(lb){lines.push(`B: y ${lb.y.toFixed(2)} m`);lines.push(`B: po zeskoku ${lb.distance.toFixed(2)} m`)}if(la&&lb){lines.push(`A−B wysokość: ${(la.y-lb.y).toFixed(2)} m`);lines.push(`A−B metry zeskoku: ${(la.distance-lb.distance).toFixed(2)} m`)}tip.innerHTML=lines.join('<br>');tip.style.display='block';tip.style.left=Math.min(mx+12,r.width-210)+'px';tip.style.top=Math.min(my+12,r.height-110)+'px';});
canvas.addEventListener('mouseleave',()=>tip.style.display='none');
function swapHills(){[hills.A,hills.B]=[hills.B,hills.A];for(const w of ['A','B']){$('name'+w).textContent=hills[w]?.name||'Brak pliku';$('params'+w).innerHTML=paramsTable(hills[w]);$('diag'+w).innerHTML=diagHtml(hills[w]);}draw();}
function clearAll(){hills={A:null,B:null};for(const w of ['A','B']){$('name'+w).textContent='Brak pliku';$('params'+w).innerHTML='<span class="small">—</span>';$('diag'+w).innerHTML='<span class="small">—</span>'}resetView()}
bindEditor();resize();loadDemo('A');
